plugins {
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
    id 'com.gradleup.shadow' version "${shadow_version}"
    id 'maven-publish'
}

apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

repositories {
    maven { url = 'https://modmaven.dev' }
}

dependencies {
    compileOnly "maven.modrinth:jei:${jei_version}"
    compileOnly "maven.modrinth:the-one-probe:${theoneprobe_version}"
    compileOnly "maven.modrinth:jade:${jade_version}"

    compileOnly "mekanism:Mekanism:${mekanism_version}:api"
    runtimeOnly "mekanism:Mekanism:${mekanism_version}"
    runtimeOnly "mekanism:Mekanism:${mekanism_version}:additions"
    runtimeOnly "mekanism:Mekanism:${mekanism_version}:generators"
    runtimeOnly "mekanism:Mekanism:${mekanism_version}:tools"

    shadow "de.maxhenkel.corelib:corelib:${minecraft_version}-${corelib_version}:api"
    runtimeOnly "de.maxhenkel.corelib:corelib:${minecraft_version}-${corelib_version}"
    compileOnly "de.maxhenkel.corelib:corelib:${minecraft_version}-${corelib_version}:javadoc"
}

processResources {
    filesMatching('**/*.toml') {
        expand 'mod_version': mod_version,
                'neoforge_dependency': neoforge_dependency,
                'minecraft_version': minecraft_version,
                'mekanism_dependency': mekanism_dependency
    }
}

shadowJar {
    relocate 'de.maxhenkel.corelib', 'de.maxhenkel.pipez.corelib'
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    manifest {
        attributes([
                "Specification-Title": "pipez",
                "Specification-Vendor": "Max Henkel",
                "Specification-Version": "1",
                "Implementation-Title": "pipez",
                "Implementation-Version": "${version}",
                "Implementation-Vendor": "Max Henkel",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
    from sourceSets.main.allJava
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact shadowJar
            artifact sourcesJar
        }
    }
    repositories {
        maven {
            name = "MyMaven"
            url = uri("https://maven.example.com/")
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}